### ISSUE TITLE
Add test.js

### ISSUE THREAD

**Issue by activenode** [FranzSkuffka/snobject#2]
A test.js needs to be added to unit-test the functionality. Code-Coverage goal: 100%.

**Comment by FranzSkuffka** [comment]
Yay!
We need to test each validation method as in valid and invalid cases.

Did you work with ava yet?
https://github.com/avajs/ava

**Comment by julianxhokaxhiu** [comment]
Done! See https://github.com/FranzSkuffka/snobject/blob/master/index.spec.js
